databases:
  - name: mdm_maker
    databaseName: mdm_maker
    user: mdm_maker

services:
  - type: web
    name: mdm_maker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mdm_maker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false